services:
  db:
    image: 'postgres:16'
    container_name: hear-me-server-pg
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=hear-me
      - POSTGRES_PORT=5433
      - POSTGRES_SSL=false
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 3s
      retries: 5